# @package _global_

callbacks:
  model_checkpoint:
    filename: "best-beta${name}"

datamodule:
  datasets:
    train:
      path: ${work_dir}/data/seq_temp/${datamodule.datasets.train.name}/train.npy
    val:
      name: ${datamodule.datasets.train.name}
      path: ${work_dir}/data/seq_temp/${datamodule.datasets.val.name}/val.npy

hydra:
  run:
    dir: logs/seq_temp/${datamodule.datasets.train.name}/
  sweep:
    dir: logs/seq_temp/multiruns/${datamodule.datasets.train.name}/
    subdir: ${hydra.job.num}

trainer:
  max_epochs: 30